### PR TITLE
AOM-51: Inform users of updates on add-ons

### PR DESCRIPTION
**Pull request by Annettesunday**
## JIRA TICKET NAME:

[AOM-51 Inform users of updates on add-ons](https://issues.openmrs.org/browse/AOM-51)

## SUMMARY:

This PR is to fix two bugs on check for updates 
- An add-on appears on the upgrade list although it is already on the latest version
- Add-ons with the same name appear on the upgrade list if any of them has an update.

These two bugs occur when more than one  add-on share a name

### CODE REVIEW

**Comment by patlub** [comment]
Looks good

**Comment by justmesam** [comment]
Looks good
👍

**Comment by jacksono** [comment]
Looks good

**Review by kwahalf — APPROVED** [review]
looks good

**Comment by dkayiwa** [comment]
@Annettesunday i have merged this because it fixes the reported problem. But like i have said on the ticket, the upgrade button does not work correctly. Though it pretends to ☺️

**Pull request merged**
