### PR TITLE
OWA-52: Implement logging for addon-manager OWA

### PR DESCRIPTION
**Pull request by jomadoye**
# JIRA TICKET NAME:
OWA-52: [Implement logging for addon-manager OWA](https://issues.openmrs.org/browse/OWA-52)

## SUMMARY:
This PR Implements logging for addon-manager OWA

### CODE REVIEW

**Comment by jomadoye** [comment]
Limitations: Currently this logger cannot generate a file and post all it's logs to the file, the reason is that the browsers do not have the permission to create a file on the system.
The appropriate fix would be to save all logs to a database and fetch it from there. A new ticket would be created to attend to this limitation.

**Comment by dkayiwa** [comment]
@andela-jomadoye can you ask your teammates to review this and tell what they think about it?

**Comment by kingisaac95** [comment]
@andela-jomadoye I have gone through the file changes and I appreciate the effort you put in doing this task. But I still believe that using console statement in production as a way to keep our logs will defeat the purpose of logging in the first place.

Logs for our application should be accessed by the developers or admin of the application to trace what went wrong, when and how it happened which we can't trace if they're logged in the console. That is the reason we need to persist it either via file or email or database storage. Also console statements shouldn't be used in production.

I did a talk on Node.js logging in production and gave a detailed description of how to use one of the tools called `winston`. The talk can be found [here](https://vimeo.com/album/4760489/video/232843715)

**Comment by jomadoye** [comment]
@kingisaac95 Thank you for your input, however, I have some point I would like to highlight.
1. Please note that `Winston` is `a multi-transport async logging library for node.js` and this is not a `Node.Js` app so we don't have the luxury of logging all server-side errors.
2. As I mentioned earlier in my first comment about the limitation of this PR, I cited that saving all the logs to a database to enable all the systems to have a single source of truth would be the ideal solution, but currently, we do not have the technical JAVA skill to implement that.
3. I am really glad you mentioned `Winston` because I think it's an awesome tool, however, this ticket was formulated because of this [OpenMRS Talk post](https://talk.openmrs.org/t/logging-for-the-open-web-app-development/13171) and I decided to build it based on the logger format in the post. 
4. Please note that there are two ways to debug an application, 1). by checking the log file, and 2). by using the console(if you are a JS developer). As such `I believe the console is an appropriate temporary solution for logging errors and stack traces` till we are able to persist it to a database/log file.
5. This PR does not use `console.log` in production. If you study the code in the [Logger.js file](https://github.com/openmrs/openmrs-owa-addonmanager/pull/20/files#diff-2c16086b56acb4e56399cdba87f6aa72) you will notice there are settings that can be used to specify the level to display error logs and stack traces and when to display them.

I would love to see what @paulupendo and @wanjikum think about this. Thank you for your invaluable input. 😊

**Comment by dkayiwa** [comment]
I do not think github will preserve these comments once the pull request is closed.
Can you guys discuss this from the talk thread where it originated?
The reason am asking is simply because am enjoying your discussion and hence would love more other developers to enjoy it too. 😊

**Comment by suthagar23** [comment]
@andela-jomadoye  How ever, you wanted to use REST again to save it to the Database. So are you plan to access the database every time to save the log? 
If you planned to do it within a time gap, what will happen if there are any lost in the conversation for the duration? 
In my view, Logging in the console will be enough for this level. 

Other Option: We can use cookies to store the logs. Let's follow this idea,
Please find the talk here : https://talk.openmrs.org/t/logging-for-the-open-web-app-development/13171/8

**Comment by jomadoye** [comment]
Closing this PR as its specification is still being discussed.

**Pull request closed without merging**
