### PR TITLE
[chore] Add search by version and developer functionality

### PR DESCRIPTION
**Pull request by wanjikum**
## JIRA TICKET NAME:
[AOM-19](https://issues.openmrs.org/browse/AOM-19)
Implement search to accommodate search by developer and version.

### SUMMARY:
The search feature only accommodates search by add on name only. It should also accommodate search by developer and version. 

I included search by description too and also added a table hover inorder to highlight the row the mouse is hovered over at.

### CODE REVIEW

**Comment by paulupendo** [comment]
Good job @wanjikum

**Comment by wanjikum** [comment]
Thank you Paul.

**Comment by dkayiwa** [comment]
@wanjikum did you notice the merge conflicts here?

**Comment by wanjikum** [comment]
I have resolved the merge conflict. Am sorry I did not see the conflict earlier.

**Comment by dkayiwa** [comment]
@wanjikum can you take a second look at this page and tell me what you see in relation to what you said above? 😊

**Comment by wanjikum** [comment]
Every time you merge a pending Pull Request, am getting a merge conflict. This is supposed to happen because my branch is behind the upstream master branch by the commit from the recent Pull request merged. 

I have resolved it.

**Pull request merged**
