### PR TITLE
AOM-79: Add loader on AddOn page

### PR DESCRIPTION
**Pull request by malmike**
## JIRA TICKET NAME:
[AOM-79: Add loader on AddOn page](https://issues.openmrs.org/browse/AOM-79)
### SUMMARY:
Add loader on add on page

### CODE REVIEW

**Review by tduyile04 — COMMENTED** [review]
Looks good

**Comment by mkiterian** [comment]
Looks good, good job

**Comment by Farhanisto** [comment]
looks good

**Comment by joel-ace** [comment]
Looks Good

**Pull request merged**
