### PR TITLE
AOM-34: Unify styling to match other OWA stylings

### PR DESCRIPTION
**Pull request by kingisaac95**
## JIRA TICKET NAME:
AOM-34 - [Different styles used for the Add-Ons Manager OWA](https://issues.openmrs.org/browse/AOM-34)

### SUMMARY:
UI styles for the big buttons has been fixed.

### CODE REVIEW

**Comment by kingisaac95** [comment]
I've fixed the tests and they're passing now, but I wanna add more features to this PR according to the description in the JIRA page. So please do not merge this yet @dkayiwa

**Comment by kingisaac95** [comment]
@dkayiwa All fixes made, you may please review now. Thanks

**Comment by jomadoye** [comment]
Looks good to me, good job @kingisaac95

**Review by chibujax — COMMENTED** [review]
Looks good.

**Comment by dkayiwa** [comment]
Can you take a look at the merge conflicts on this?

**Comment by kingisaac95** [comment]
@dkayiwa Done

**Pull request merged**
