### PR TITLE
AOM-24: Ensure all .jsx components and file names begin with a capital letter

### PR DESCRIPTION
**Pull request by jomadoye**
# JIRA TICKET NAME:
AOM-24: [Ensure all .jsx components and file names begin with a capital letter](https://issues.openmrs.org/browse/AOM-24)

## SUMMARY:
This PR ensures that all .jsx files and components begin with a capital letter, as this is a good design practice in react.

### CODE REVIEW

**Comment by kingisaac95** [comment]
Looks okay @andela-jomadoye. I was worried about this => `app/js/Openmrs-addonmanager.jsx` but since it's auto generated, we can let it be. 👍

**Comment by chibujax** [comment]
Does this follow the react guide? If yes, everything looks good. cc @dkayiwa

**Comment by jomadoye** [comment]
Yes it does @andela-cuchendu, The link to the style rule can be found [HERE](https://github.com/airbnb/javascript/tree/master/react#naming)

**Comment by dkayiwa** [comment]
@andela-jomadoye can you share this with the rest of the andela devs?

**Pull request merged**
