### PR TITLE
AOM-101: Some installed modules display install button

### PR DESCRIPTION
**Pull request by malmike**
## JIRA TICKET NAME:
[AOM-101: Some installed modules display install button](https://issues.openmrs.org/browse/AOM-101)
### SUMMARY:
When a user clicks on a module to install, after installation the module is expected to install and have the view button displayed instead of install/download button

### CODE REVIEW

**Comment by kodero** [comment]
The CI build failed.

**Comment by malmike** [comment]
Fixed the CI build issue

**Review by aenkya — COMMENTED** [review]
LGTM

**Comment by justmesam** [comment]
Looks Good

**Comment by Annettesunday** [comment]
Looks good 👍

**Pull request merged**
