### PR TITLE
AOM-49: Fix Img error 404 bug

### PR DESCRIPTION
**Pull request by jomadoye**
# JIRA TICKET NAME:
AOM-49: [Fix Img error 404 bug](https://issues.openmrs.org/browse/AOM-49)

## SUMMARY:
This PR aims to fix the openMRS image 404 bug by adding a path to it in the module bundling file

### CODE REVIEW

**Comment by kingisaac95** [comment]
👍

**Comment by paulupendo** [comment]
Good job Jed.

**Comment by jomadoye** [comment]
@dkayiwa The PR is ready.

**Comment by wanjikum** [comment]
Looks good @andela-jomadoye

**Pull request merged**
