### PR TITLE
AOM-69: Add a button to start all modules

### PR DESCRIPTION
**Pull request by mkiterian**
## JIRA TICKET NAME:
[AOM-69 Add a button to start all modules](https://issues.openmrs.org/browse/AOM-69)
### SUMMARY:
This PR adds functionality to start all modules by clicking on a start all button in the Add-on Manager Manage Apps page.

### CODE REVIEW

**Review by tduyile04 — COMMENTED** [review]
Great job!!! Looks good.

**Comment by Farhanisto** [comment]
Nice Job

**Review by malmike — COMMENTED** [review]
Looks good

**Comment by joel-ace** [comment]
Looks Good

**Comment by kodero** [comment]
LGTM

**Comment by dkayiwa** [comment]
Can you take a look at these merge conflicts?

**Pull request merged**
