### PR TITLE
AOM-121: The add-on listings should be displayed in an alphabetical order

### PR DESCRIPTION
**Pull request by Annettesunday**
## JIRA TICKET NAME:

[AOM-121 The add-on listings should be displayed in an alphabetical order](https://issues.openmrs.org/browse/AOM-121)

## SUMMARY:
All listings for add-ons whether for searches, default list and updates should be arranged in an alphabetical order for consistency and user friendliness.

### CODE REVIEW

**Comment by Charpell** [comment]
Looks good to me

**Review by segunolalive — COMMENTED** [review]
Looks good

**Comment by malmike** [comment]
Looks good to me

**Comment by dkayiwa** [comment]
@Annettesunday do you know why openmrs-addOnManager is listed last?

**Comment by Annettesunday** [comment]
@dkayiwa Due to case sensitivity

**Comment by dkayiwa** [comment]
Can you make it case insensitive?

**Comment by Annettesunday** [comment]
@dkayiwa I have already

**Comment by dkayiwa** [comment]
Did you attach the updated app on the ticket?

**Comment by Annettesunday** [comment]
yes @dkayiwa

**Comment by patlub** [comment]
Looks good to me

**Pull request merged**
