### PR TITLE
AOM-32: Add a coveralls badge

### PR DESCRIPTION
**Pull request by wanjikum**
## JIRA TICKET NAME:

[AOM-32](https://issues.openmrs.org/browse/AOM-32)
Add a coveralls badge

### SUMMARY:
This helps us get the overall test coverage of our project.

### CODE REVIEW

**Comment by jomadoye** [comment]
Looks good, Good job @wanjikum

**Comment by wanjikum** [comment]
Thank you, @andela-jomadoye.

**Review by chibujax — COMMENTED** [review]
Config looks good

**Comment by kingisaac95** [comment]
Good job @wanjikum

**Pull request merged**
