### PR TITLE
AOM-95: Change installation REST endpoint from moduleinstall to moduleaction

### PR DESCRIPTION
**Pull request by mkiterian**
## JIRA TICKET NAME:
[AOM-95 Change installation REST endpoint from moduleinstall to moduleaction](https://issues.openmrs.org/browse/AOM-95)

### SUMMARY:
The REST end point for installation was changed on [RESTWS-688](https://issues.openmrs.org/browse/RESTWS-688) based on review recommendations, this ticket reflects the same change on the front end

### CODE REVIEW

**Comment by Charpell** [comment]
Looks good to me

**Comment by patlub** [comment]
Looks good to me

**Comment by Annettesunday** [comment]
Good job:)

**Comment by Farhanisto** [comment]
Looks good

**Comment by malmike** [comment]
Looks good

**Pull request merged**
