### PR TITLE
AOM-44: Persist location information in header

### PR DESCRIPTION
**Pull request by jomadoye**
# JIRA TICKET NAME:
AOM-44: [Persist location information in header](https://issues.openmrs.org/browse/AOM-44)

## SUMMARY:
This PR aims to Persist location information in header

### CODE REVIEW

**Comment by jomadoye** [comment]
@kingisaac95 @wanjikum @paulupendo Please kindly review this PR.

**Review by wanjikum — COMMENTED** [review]
looks good

**Comment by kingisaac95** [comment]
Nice

**Comment by dkayiwa** [comment]
The ticket link does not look correct.

**Comment by jomadoye** [comment]
That was an oversight, sorry about that @dkayiwa. I've fixed it now.

**Pull request merged**
